---
- name: Install Python
  sudo: true
  yum: pkg={{ item }} enablerepo=epel state=present
  with_items:
    - python
    - python-pip
  tags:
    - app-deps

- name: Pull fresh version from repository
  shell: cd {{ app_path }} && git pull
  tags:
    app-pull

- name: Install Python dependencies
  shell: pip install -r {{ app_path }}/requirements.txt
  tags:
    - app-deps

- name: Install init script
  template: src=templates/systemd.service dest=/etc/systemd/system/{{ app_name }}.service mode=0644
  tags:
    - app-init

- name: systemctl-reload
  sudo: true
  shell: systemctl daemon-reload
  tags:
    - app-init

- name: restart {{ app_name }}
  service: name={{ app_name }} state=started
